apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-oidc-issuer-reflector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-oidc-issuer-reflector
  template:
    metadata:
      labels:
        app: kube-oidc-issuer-reflector
    spec:
      containers:
      - name: kube-oidc-issuer-reflector
        image: ghcr.io/kangarookube/kube-oidc-issuer-reflector:7d18d24
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-oidc-issuer-reflector
spec:
  selector:
    app: kube-oidc-issuer-reflector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-oidc-issuer-reflector
annotations:
  kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: $ISSUER_FQDN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-oidc-issuer-reflector
            port:
              number: 80
